### ISSUE TITLE
Getting internal server error after logging

### ISSUE THREAD

**Issue by joshedney** [richardtatum/gif_board#2]
Getting the following error when logging in.

```[2019-03-16 21:13:26,360] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/routes.py", line 31, in login
    if not next_page or url_parse(next_page).netloc != '':
NameError: name 'url_parse' is not defined
```

**Comment by joshedney** [comment]
Need to import `werkzeug.urls`

**Comment by joshedney** [comment]
Created a PR to fix this if you would like to merge it.

https://github.com/richardtatum/gif_board/pull/3

**Comment by richardtatum** [comment]
Completed in #3
